#! /bin/sh

sxhkd &
feh --bg-fill /home/fernando/Wallpapers/07.png &
wmname LG3D &
~/.config/polybar/launch.sh --blocks  &
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor HDMI1 -d I II III IV V VI VII  
 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config border_width 1.5

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating
picom --experimental-backends &
